[package]
name = "TrusDB"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
log = "0.4.28"
env_logger = "0.11.8"
dotenv = "0.15.0"
chrono = "0.4.42"
